### ISSUE TITLE
Add redis min. required version.

### ISSUE THREAD

**Issue by x-N0** [bitcart/bitcart-docs#1]
Context: Following the docs manual deployment, while executing Dramatiq (-V '1.9.0').

Issue: 
```red
Error: redis.exceptions.ResponseError: unknown command 'EVALSHA';
```

Used: Redis V2.
Executed script: `dramatiq api.tasks`
Solved: Updated redis to V5.

Possible solution: Look throughout the [Redis](https://redis.io/) docs to find when the command 'EVALSHA' was added and almost add that version to the docs as a min. required.

**Comment by MrNaif2018** [comment]
It was added in redis 2.6.0
Redis 2.6.0 was released back in 2013: https://raw.githubusercontent.com/antirez/redis/2.6/00-RELEASENOTES
There are even redis 5 and 6 available now.
Issues about it are from 2014 too.
Any decent redis version should work, I don't think we should clarify it

**Comment by x-N0** [comment]
For windows there's no official release, so the Redis provided from the official documentation is really old (-V 2.4).
Here> [Redis Windows Release](https://github.com/dmajkic/redis/downloads)
So I think every new contributor should know that so they don't need to ask.
And also search for an unofficial updated release like >[Redis Unofficial Release (-V 5.0)](https://github.com/tporadowski/redis)

What do you think about it?
It's about time and pragmatism.

**Comment by MrNaif2018** [comment]
I think that windows isn't suitable for development using such crucial architecture parts as redis and postgres especially.
At least in it's standard form.
Windows users should run redis in docker, or use port of redis (there is 3.0, 5.0 port, it's quite easy to find any decent version), or windows users should just use wsl2, which was created for this. But windows will never be as easy to use as unixes for development (:
There are still lots of solutions, google search for redis on windows almost instantly brings to redis 5.0, which is decent enough.
If in the future we use some more specific redis version, like 5.0 or even 6.0, then it's worth clarifying. But for 2.6.0 minimum-I think no need

**Comment by x-N0** [comment]
Well, let's see, whaddup.
