### ISSUE TITLE
Hacktoberfest welcome

### ISSUE THREAD

**Issue by MrNaif2018** [bitcart/bitcart-docs#5]
Main welcome: bitcartcc/bitcart#243

Issue list:

- [ ] #3 
- [ ] #4

**Comment by rishitc** [comment]
Hi,

Can you provide a list of use cases, that we need to cover in the videos.

Thanks.

**Comment by MrNaif2018** [comment]
Hi! Sure. You can find many use cases described here:
https://docs.bitcartcc.com/bitcartcc-basics/use-case
Merchants and developers are main use cases, you can find more detailed descriptions there
Not all use cases described were already tried by community, but a few online stores and hosting providers already use us
Let me know if you have any other questions

**Comment by MrNaif2018** [comment]
Hi @rishitc! Did you succeed in creating a video about BitcartCC? Let me know if you need some help
